baseURL = "https://hlth460uc.netlify.com/"
languageCode = "en-us"
title = "Critical appraisal for health research"
[permalinks]
    post = "/:year/:month/:day/:slug"

theme = "blackburn"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$",
               "_files$", "_cache$"]

uglyURLs = true

[params]
    author = "Arindam Basu"

